# Arquivo: backend/Dockerfile

# Estágio de Build
FROM maven:3.9-eclipse-temurin-20 AS builder
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests

# Estágio Final
FROM eclipse-temurin:20-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]